[package]
name = "bitvec"
version = "0.1.0"
authors = ["William Kraft <william.z.kraft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
